import type { BrowserSelectionContext } from '../../utils/browser';
import type { CanvasSelectionContext } from '../../utils/canvas';
import type { EditorSelectionContext } from '../../utils/editor';
import type {
  ApprovalDecision,
  Conversation,
  ExitPlanModeCallback,
  ImageAttachment,
  StreamChunk,
} from '../types';

export interface ApprovalDecisionOption {
  label: string;
  description?: string;
  value: string;
  decision?: ApprovalDecision;
}

export interface ApprovalNetworkContext {
  host: string;
  protocol: string;
}

export interface ApprovalCallbackOptions {
  decisionReason?: string;
  blockedPath?: string;
  agentID?: string;
  decisionOptions?: ApprovalDecisionOption[];
  networkApprovalContext?: ApprovalNetworkContext;
  additionalPermissions?: unknown;
}

export type ApprovalCallback = (
  toolName: string,
  input: Record<string, unknown>,
  description: string,
  options?: ApprovalCallbackOptions,
) => Promise<ApprovalDecision>;

export type AskUserQuestionCallback = (
  input: Record<string, unknown>,
  signal?: AbortSignal,
) => Promise<Record<string, string | string[]> | null>;

export interface ChatTurnRequest {
  /**
   * Single-source turn identifier. Generated by the feature layer
   * (InputController) for user turns and threaded unchanged through
   * PreparedChatTurn → runtime turn registry → message channel lease.
   * Providers must not reinterpret or regenerate it.
   */
  turnId: string;
  text: string;
  images?: ImageAttachment[];
  currentNotePath?: string;
  editorSelection?: EditorSelectionContext | null;
  browserSelection?: BrowserSelectionContext | null;
  canvasSelection?: CanvasSelectionContext | null;
  externalContextPaths?: string[];
  enabledMcpServers?: Set<string>;
}

export interface PreparedChatTurn {
  /** Verbatim copy of ChatTurnRequest.turnId. Encoders must not regenerate it. */
  turnId: string;
  request: ChatTurnRequest;
  persistedContent: string;
  prompt: string;
  isCompact: boolean;
  mcpMentions: Set<string>;
}

export interface ChatRuntimeQueryOptions {
  allowedTools?: string[];
  model?: string;
  mcpMentions?: Set<string>;
  enabledMcpServers?: Set<string>;
  forceColdStart?: boolean;
  externalContextPaths?: string[];
}

export interface ChatRuntimeEnsureReadyOptions {
  allowSessionCreation?: boolean;
  force?: boolean;
}

export type ChatRuntimeConversationState = Pick<
  Conversation,
  'sessionId' | 'providerState'
>;

export interface SessionUpdateResult {
  updates: Partial<Conversation>;
}

export interface ChatRewindResult {
  canRewind: boolean;
  error?: string;
  filesChanged?: string[];
  insertions?: number;
  deletions?: number;
}

export interface SubagentRuntimeState {
  hasRunning: boolean;
}

/**
 * Fix 2 (通知直接销账): handler invoked when a harness task-notification
 * arrives on the live message stream. taskId equals the agentId of the
 * async subagent; status is the raw notification status string.
 */
export type SubagentTaskNotificationHandler = (
  taskId: string,
  status: string,
  result?: string | null,
) => void;

export interface ChatTurnMetadata {
  userMessageId?: string;
  assistantMessageId?: string;
  wasSent?: boolean;
  planCompleted?: boolean;
}

export interface AutoTurnResult {
  chunks: StreamChunk[];
  metadata: ChatTurnMetadata;
}

/**
 * S2 provider-neutral auto-turn lifecycle. Sync payload fired when a runtime
 * starts an SDK-initiated (auto) turn; the feature layer takes its exclusive
 * turn lease here (v4 §6: strictly before the notification is dispatched).
 */
export type AutoTurnSource =
  | { kind: 'peer'; label?: string }
  | { kind: 'channel'; label?: string }
  | { kind: 'coordinator' }
  | { kind: 'notification-continuation' }
  | { kind: 'assistant-continuation' };

export interface AutoTurnStartedEvent {
  turnId: string;
  generation: number;
  source: AutoTurnSource;
  /** Sanitized user-visible text; never contains transport/control metadata. */
  displayContent?: string;
  transcriptUserId?: string;
  replay?: boolean;
}

export interface AutoTurnChunkEvent {
  turnId: string;
  generation: number;
  chunk: StreamChunk;
  transcriptIdentity?: string;
  replay?: boolean;
}

export interface AutoTurnDiagnosticEvent {
  phase: 'tick_start' | 'tick_end' | 'map' | 'lease_begin' | 'lease_finish' | 'lease_release'
    | 'render_start' | 'render_end' | 'save_start' | 'save_end' | 'save_timeout' | 'callback_error';
  turnId?: string;
  generation?: number;
  leaseKind?: 'user' | 'auto';
  batchBytes?: number;
  batchLines?: number;
  elapsedMs?: number;
  errorName?: string;
}

export interface AutoTurnFinishedEvent {
  turnId: string;
  generation: number;
  metadata: ChatTurnMetadata;
  replay?: boolean;
  /** Byte offset of the transcript row that established completion. */
  terminalOffset?: number;
  /** A later host user row makes this completion a delayed report. */
  supersededByHostUser?: boolean;
}

/**
 * Fired when a runtime cancels an SDK-initiated (auto) turn (v3 §4.2).
 * `interrupted` marks a turn terminated without an end marker (transcript
 * replaced / observer stopped mid-turn): the projection must not report
 * completion (v6 §4.3 crash semantics).
 */
export interface AutoTurnCancelledEvent {
  turnId: string;
  generation: number;
  reason: string;
  interrupted?: boolean;
}

export type {
  ApprovalDecision,
  ExitPlanModeCallback,
};
